#
#       = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
#       =: = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = :=
#       ::                                                                             ::
#       ::   #####                                      #####                          ::
#       ::  #     # ###### #####  #    # ###### #####  #     # #  ####  #    #  ####   ::
#       ::  #       #      #    # #    # #      #    # #       # #    # ##   # #       ::
#       ::   #####  #####  #    # #    # #####  #    #  #####  # #      # #  #  ####   ::
#       ::        # #      #####  #    # #      #####        # # #  ### #  # #      #  ::
#       ::  #     # #      #   #   #  #  #      #   #  #     # # #    # #   ## #    #  ::
#       ::   #####  ###### #    #   ##   ###### #    #  #####  #  ####  #    #  ####   ::
#       ::                                                                             ::
#       =: = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = :=
#       = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
#                               
#       you can use color codes (prefix: &) for layout contents
#       and following variables:
#
#       %servername% - Shows the name of the server
#       %motd% - Shows the actual server motd
#       %online% - Shows the actual number of online players on the server
#       %max% - Shows the number of maximum players on server
#
#
serversigns:
# it's the best if you don't change signsdata!
  signsdata:
  - exampleserver;examplelayout;world,0.0,0.0,0.0
  layouts:
    examplelayout:
      line1: line1
      line2: line2
      line3: line3
      line4: line4
  servers:
    exampleserver:
      ip: localhost
      port: 25565
  cycleupdate: 20
#         ^ in ticks ^
